apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "coderank_auth"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abhinav195"
          volumeMounts:
            - name: postgres-auth-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderank_auth"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderank_auth"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: postgres-auth-data
          persistentVolumeClaim:
            claimName: postgres-auth-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-problem-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-problem
spec:
  selector:
    app: postgres-problem
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-problem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-problem
  template:
    metadata:
      labels:
        app: postgres-problem
    spec:
      containers:
        - name: postgres-problem
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "coderankproblem"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abhinav195"
          volumeMounts:
            - name: postgres-problem-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderankproblem"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderankproblem"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: postgres-problem-data
          persistentVolumeClaim:
            claimName: postgres-problem-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-submission-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-submission
spec:
  selector:
    app: postgres-submission
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-submission
  template:
    metadata:
      labels:
        app: postgres-submission
    spec:
      containers:
        - name: postgres-submission
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "coderank_submission"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abhinav195"
          volumeMounts:
            - name: postgres-submission-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderank_submission"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "coderank_submission"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: postgres-submission-data
          persistentVolumeClaim:
            claimName: postgres-submission-data